name: Build Docker image

on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME  }}/${{ secrets.DOCKER_REPO_NAME }}
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_BUILDKIT: 1
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: |-
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set tag in environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build multi-arch image and push release tag
        if: contains(github.ref, 'refs/tags/')
        run: |-
          docker buildx build \
            --cache-from=$IMAGE_NAME:latest \
            --push \
            -t $IMAGE_NAME:$RELEASE_VERSION \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
            .
